### PR TITLE
Added non-wrapper GUI

### PR DESCRIPTION
**Pull request by ghost**
- Easy to use Interface
- No hard to remember commands
- Tkinter based ttk interface for simplicity and beauty
- Interactive File Browser
- The double-starred fields are optional and can be left blank
- Remember Me Check Button added
- doesn't affect existing users as GUI is totally optional

dl

Feedback would be much appreciated.

### CODE REVIEW

**Comment by ghost** [comment]
Fixed custom html parsers bug in commit 9b151b5

**Comment by dgorissen** [comment]
Thanks for this. I have had a first quick look through. Main comment: I would like to keep the original script and the gui separate which means avoiding the base script having a dependence on tk/gui (so that those dependencies remain optional). So I would suggest writing your gui script as a wrapper that wraps the original one without introducing extra dependencies or impacting existing users (if the gui is no longer maintained for some reason for example). I will refactor the original script a bit so its cleaner and provides the necessary hooks. Your gui can then be deployed as a separate script (coursera-dl-gui or something).

**Comment by ghost** [comment]
@dgorissen yeah That would be better for everyone, I will make the necessary changes but it'll take some time as I'm sorta busy these days

**Comment by ghost** [comment]
I rewrote the code using the latest commit 9dfcc2865c348fc10f5600324346902d8bce8119, Now the GUI is just a wrapper for the script and wouldn't have any effect on existing users, To run the GUI just execute `GUI.py` . _I haven't tested the GUI on linux_, anyway I hope you find the latest piece of code interesting and hope to hear any feedback :)

**Comment by ghost** [comment]
```
$ python courseradownloader/GUI.py # 834c2e8ff
```

It works, but it's ugly.


- It won't let me Right Click > Paste
- It won't let me "Create new folder" from the folder switcher (and is unclear that it creates one itsself)

Throws this if I don't do 'select folder' before the continue button

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "courseradownloader/GUI.py", line 76, in submit_data
    self.data = [self.username.get(),self.password.get(),self.courseName.get().split(),self.destination,self.ignoreFiles.get(),self.pro    xy,self.trim.get(),self.reverse.get(),self.parser_mod]
AttributeError: Interface instance has no attribute 'destination'
```

**Comment by ghost** [comment]
@zamabe I haven't tested this on any other OS than windows, and I'm currently busy and I'm considering revamping and upgrading so that not a single line in `courseradownloader.py` is affected which would, hopefully also fix that certain issue. Also please do help to add GUI **if possible** to this branch or [my branch](https://github.com/K-DawG007/coursera-dl)

Therefore I'm closing this pull request...

**Pull request closed without merging**
