### PR TITLE
Checking that the download file path does not exceed max length

### PR DESCRIPTION
**Pull request by bijujosephjacob**
Hit issues on Windows with max path lengths - noticed that most of the code was already in place, but not used.

### CODE REVIEW

**Comment by bijujosephjacob** [comment]
Hey, have you got a chance to look into this as yet?

**Comment by dgorissen** [comment]
Thanks!

**Comment by bijujosephjacob** [comment]
No probs, please let me know when you release the version for installation via pip. Thanks!

**Comment by bijujosephjacob** [comment]
Hey Dirk, please let me know when this version (v. 3.1.0.0) is made available for installation via pip. I can remove my fork then. Thanks!

**Comment by dgorissen** [comment]
done

**Pull request merged**
