### PR TITLE
Option to exclude files from downloading

### PR DESCRIPTION
**Pull request by ckotso**
Added -n command line option to exclude files from downloading, based on filename extension (e.g. srt, ppt).

### CODE REVIEW

**Comment by dgorissen** [comment]
Thanks for the patch, could you just elaborate on the usecase, I would image you typically would like to keep everything. Is it subtitles you are looking to skip?

**Comment by ckotso** [comment]
Yes, it's about the subtitles. Using VLC, one has to keep disabling subtitles for each clip once it starts playing -- or must globally disable auto-loading subtitles, which is also suboptimal.
But someone else may not care about slides, notes, etc, so I assume it's not too bad to have the option.

**Comment by dgorissen** [comment]
mmm so the usecase is driven by the default behaviour of a particular media player which is a bit things on its head :)  Note you can turn on/off subtitles in VLC by simply hitting the "v" key. Im not convinced there are many users for this feature (happy to be proven otherwise though) but then again it requires only small changes to the code. I will think about how it relates to issue #21 and then fix both together.

**Comment by ckotso** [comment]
Well, you are assuming that there is a keyboard to begin with :) But in fact I am viewing videos on my HTPC with either VLC or XBMC, using something like the MS Media Center Remote Control (no keyboard) to navigate. Switching subs on/off is a real pain, independent of the video player. Mapping some hardware key may be an option but other users may be uncomfortable with this...

**Pull request closed without merging**
